### ISSUE TITLE
calling smatch.match incorrectly may take a long time before throwing an exception

### ISSUE THREAD

**Issue by erykoff** [esheldon/smatch#1]
The proper calling sequence is
`smatch.match(ra1,dec1,radius,ra2,dec2)`

But let's say you are (a) matching a list to itself and (b) porting code from htm and make a mistake.  If you call with:
`smatch.match(ra,dec,ra,dec,radius)`

Then the first check (length of first ra is the same as first dec is the same as the "radius") passes, but then it tries to build a tree with radii set by the RA values, which can be quite large and can take a very long time.  Eventually (presumably it'll finish in some finite amount of time) it builds the tree and then throws an exception since the length of the second ra is not the same as the second dec (since this was called with a scalar radius).

This particular failure mode could be averted if the ra1/dec1/radius and ra2/dec2 lengths are all checked before initializing the Catalog.

(In the case that the radius also has the same length, this failure to rtfm will still not throw an exception).

**Comment by esheldon** [comment]
OK, so we should add those checks.  Feel like making a pull request?

Also could make these keywords to make it less ambiguous.

**Comment by erykoff** [comment]
Don't have time today to fork and fix, but should be able to this week.  Will keywords break my existing code?

**Comment by esheldon** [comment]
yes

on the other hand, probably no one else uses this code but us, so only we need to fix our codes

**Comment by esheldon** [comment]
actually this repo has some stars, so that's not true

**Comment by esheldon** [comment]
I just pushed a change that addresses this, please test.

**Comment by esheldon** [comment]
Is this working now for you?
