### ISSUE TITLE
special case matching a catalog to itself

### ISSUE THREAD

**Issue by esheldon** [esheldon/smatch#2]
from @erykoff 

it would be nice to special case matching a catalog to itself so that the self match is not included in the output, only neighbors are.

**Comment by esheldon** [comment]
One way is to just reject things with the same index

Would this be better served by a minimum radius option?  Then catalogs with slightly different astrometry could still be handled in this way.

**Comment by erykoff** [comment]
Hmm.  I guess a minimum radius option with some tiny minimum would serve the same option.  But there's something cleaner in my mind about integer matching to reject things with the same index if requested.

**Comment by esheldon** [comment]
I agree.  Maybe do index matching first

**Comment by esheldon** [comment]
Check out the branch selfmatch

**Comment by erykoff** [comment]
Seems to work as advertised.  Trying to figure out if this actually helps in the way I use smatch, but it does work.

**Comment by esheldon** [comment]
I thought this was something you requested at some point....

**Comment by erykoff** [comment]
Well, I just wanted to know if the matching could be made faster and/or less memory if you know that the two catalogs are the same...certainly it's fewer typos if you only have to type in one catalog.  But now that I see it, does it actually help?

**Comment by esheldon** [comment]
I see.

It is not faster.

It will use less memory for the matches, since there are fewer matches.

**Comment by esheldon** [comment]
I will say that this would have removed some confusion in some cases where people were doing matches and were using the self match when they should not have

**Comment by esheldon** [comment]
merged
